### ISSUE TITLE
Depends on 767 Goldhofert

### ISSUE THREAD

**Issue by FGDATA** [FGMEMBERS/A350XWB#1]
Legoboy wrote:

---

> "Cannot open C:/Program Files/Flightgear 3.4.0/Data/Aircraft/767/Models/Pushback/goldhofert.xml"

**Comment by FGDATA** [comment]
fixed with afd2562156c653f4093819f2fba1129657306973
Thanks for reporting SW

**Comment by legoboyvdlp** [comment]
Thanks! I'll let him know.
