### ISSUE TITLE
UV Mapping wrong?

### ISSUE THREAD

**Issue by legoboyvdlp** [FGMEMBERS/A350XWB#3]
When you look round the cockpit, you see parts of the livery...

**Comment by FGDATA** [comment]
ok. Prob. nothing to do the the mapping thou.
Can you post screenshot?

**Comment by legoboyvdlp** [comment]
Sure, will do tomorrow.
It is very obvious on loading the a/c though, especially in Avianca livery :)

**Comment by ghost** [comment]
I think it is due to the livery selector texturing things that it shouldn't. Maybe things with similar or identical names as outside parts. Will check it out eventually.

**Comment by RenanMsV** [comment]
Fixed! Uhuh http://imgur.com/a/tf240
Causes: fuselage and others models with same child names.

**Comment by tonghuix** [comment]
It seems the PR #14 fixed the bug and other improvement.

**Comment by FGDATA** [comment]
:+1:
