### ISSUE TITLE
AIRCRAFT NOT READY.

### ISSUE THREAD

**Issue by kalistarv8** [FGMEMBERS/A350XWB#7]
Nothing is working..No landing gear..incomplete OH Panel. Good exterior model..Please update

**Comment by FGDATA** [comment]
Thanks for the report
Could you please verify this 
https://github.com/FGMEMBERS/A350XWB/archive/c685606a2324f05e42fa1d046ee79652530de884.zip
and tell me if that version works better?

IH-COL

**Comment by legoboyvdlp** [comment]
Hi @kalistarv8. Why don't you give it a go? :) Try and make it better!

**Comment by ghost** [comment]
Alot is working now. I and others have done quite a bit of work on it. It is flyable.
